language: bash

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG0=latest
  - export TAG1=`cat ./.version`
  - docker build -t $REPO:$TAG0 .
  - docker build -t $REPO:$TAG1 .
  - docker push $REPO:$TAG0
  - docker push $REPO:$TAG1